<?php
session_start();
unset($_SESSION['sess_user']);
unset($_SESSION['sess_selected_train_no']);
unset($_SESSION['sess_train_name']);
unset($_SESSION['sess_station_from']);
unset($_SESSION['sess_departure_time_from']);
unset($_SESSION['sess_station_to']);
unset($_SESSION['sess_arrival_time_to']);
unset($_SESSION['sess_seat_category']);
unset($_SESSION['sess_available_date']);
unset($_SESSION['sess_seat']);
unset($_SESSION['sess_fare']);
setcookie("cook_user",$_POST["user"],time()-(3*60));
setcookie("cook_pass",$_POST["pass"],time()-(3*60));
session_destroy();
header("location:home.php");
?>
